wxm.layout.cascade.AtomContainer=Spine.Controller.create({
	init:function(options){
		this.nextEl=$("<div>");
	},
	setPrevious:function(previous){
		this.previous=previous;
		this.previous&&(this.previous.next=this);
	},
	render:function(){
		this.el.append(this.nextEl);
	}
});