wxm.layout.cascade.AtomContainer=wxm.layout.AbstractContainer.create({
	init:function(options){
		this.nextEl=$("<div>");
		this.routeFragment=options.fragment;
	},
	setPrevious:function(previous){
		this.previous=previous;
		this.previous&&(this.previous.next=this);
	},
	render:function(){
		this.el.append(this.nextEl);
	}
});